#!/usr/bin/env python

from blessings import Terminal
import requests
from datetime import datetime
import os
import time


def main():
    t = Terminal()
    oldfilename = None
    current_folder = os.path.dirname(os.path.abspath(__file__))
    files = os.path.join(current_folder, 'files')
    if not os.path.isdir(files):
        try:
            os.mkdir(files)
        except OSError:
            print "Please delete the file called `files`"
            return
    while True:
        r = requests.get('https://www.streamtext.net/player/'
                         'carttranscript?Event=WIPO')
        print "Requested"
        filename = os.path.join(current_folder, 'files',
                                ''.join([str(datetime.utcnow()), '.txt']))
        print "Writing to {t.green} {filename} {t.normal}".format(
                t=t, filename=filename)
        with open(filename, 'w') as f:
            f.write(r.text)
        if oldfilename:
            statfile = os.stat(filename)
            statoldfile = os.stat(oldfilename)
            if statfile.st_size >= statoldfile.st_size:
                os.remove(oldfilename)
                print "Deleting: {t.red} {filename} {t.normal}".format(
                        t=t, filename=oldfilename)
            if statfile.st_size == statoldfile.st_size:
                print ("{t.bold}{t.blue}No change in file "
                       "size{t.normal}".format(t=t))
        oldfilename = filename
        time.sleep(5)



if __name__ == '__main__':
    main()
