#!/usr/bin/env python

# Copyright (C) 2013 Nigel Babu

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from blessings import Terminal
import requests
from datetime import datetime
import os
import time


def main():
    t = Terminal()
    oldfilename = None
    current_folder = os.path.dirname(os.path.abspath(__file__))
    files = os.path.join(current_folder, 'files')
    if not os.path.isdir(files):
        try:
            os.mkdir(files)
        except OSError:
            print "Please delete the file called `files`"
            return
    while True:
        r = requests.get('https://www.streamtext.net/player/'
                         'carttranscript?Event=WIPO')
        print "Requested"
        filename = os.path.join(current_folder, 'files',
                                ''.join([str(datetime.utcnow()), '.txt']))
        print "Writing to {t.green} {filename} {t.normal}".format(
                t=t, filename=filename)
        with open(filename, 'w') as f:
            f.write(r.text)
        if oldfilename:
            statfile = os.stat(filename)
            statoldfile = os.stat(oldfilename)
            if statfile.st_size >= statoldfile.st_size:
                os.remove(oldfilename)
                print "Deleting: {t.red} {filename} {t.normal}".format(
                        t=t, filename=oldfilename)
            if statfile.st_size == statoldfile.st_size:
                print ("{t.bold}{t.blue}No change in file "
                       "size{t.normal}".format(t=t))
        oldfilename = filename
        time.sleep(5)



if __name__ == '__main__':
    main()
